name: 'Tencent Cos cli'
description: 'Tencent Cos cli'
inputs:
  version:
    description: 'The version number of cos cli'
    required: false
    default: '0.13.0'
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install coscli cli
      shell: bash
      run: |
        # install coscli
        curl -o /usr/local/bin/coscli https://cosbrowser-1253960454.cos.ap-shanghai.myqcloud.com/software/coscli/coscli-linux
        # set permission
        chmod +x /usr/local/bin/coscli

        # debug
        ls -alh /usr/local/bin
        coscli -version

    
