name: 'Tencent Cos cli'
description: 'Tencent Cos cli'
inputs:
  version:
    description: 'The version number of cos cli'
    required: false
    default: '0.13.0'
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install aliyun cli
      shell: bash
      run: |
        # install coscli
        curl -sL https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux /usr/local/bin --strip-components=1 coscli
    
