name: coscli test workflow
on: [push]
jobs:
  hello:
    name: test coscli
    runs-on: ubuntu-latest
    env:
      COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
      COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      COS_BUCKET: ${{ secrets.COS_BUCKET }}
      COS_REGION: ${{ secrets.COS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use coscli
        uses: afeiship/action-coscli@master

      - name: Debug
        run: |
          #check env
          printenv
          coscli --version

          # check .cos.yml file exists
          cd ~
          ls -alh